name: build app
on:
  push:
    branches:
      - '*'
jobs:
  build-webapp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cd app && npm install && npm run build
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: cd server && npm install && npx -y tsc
  test-docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down